
const nomesUnidades = [
    { ds: 5, nomeUnidade: 'US 117 USF GASPAR REGUEIRA COSTA (BARRO)'},
    { ds: 5, nomeUnidade: 'US 142 USF BIDU KRAUSE'},
    { ds: 5, nomeUnidade: 'US 150 CS PROFESSOR FERNANDES FIGUEIRAS'},
    { ds: 5, nomeUnidade: 'US 158 CS PAM CEASA'},
    { ds: 5, nomeUnidade: 'US 161 CS PROF ROMERO MARQUES'},
    { ds: 5, nomeUnidade: 'US 177 USF CHICO MENDES'},
    { ds: 5, nomeUnidade: 'US 186 USF JARDIM UCHÔA'},
    { ds: 5, nomeUnidade: 'US 238 USF IRAQUE'},
    { ds: 5, nomeUnidade: 'US 239 USF COQUEIRAL I E II'},
    { ds: 5, nomeUnidade: 'US 245 USF PLANETA DOS MACACOS II'},
    { ds: 5, nomeUnidade: 'US 265 USF MANGUEIRA I'},
    { ds: 5, nomeUnidade: 'US 266 USF MANGUEIRA II'},
    { ds: 5, nomeUnidade: 'US 284 USF VILA SÃO MIGUEL MARROM GLACÊ'},
    { ds: 5, nomeUnidade: 'US 294 USF VILA TAMANDARE BEIRINHA'},
    { ds: 5, nomeUnidade: 'US 300 USF DR GERALDO B CAMPELO SAN MARTIN'},
    { ds: 5, nomeUnidade: 'US 301 USF BONGI BOA IDEIA'},
    { ds: 5, nomeUnidade: 'US 323 USF MUSTARDINHA'},
    { ds: 5, nomeUnidade: 'US 338 USF JARDIM SÃO PAULO'},
    { ds: 5, nomeUnidade: 'US 344 USF JIQUIÁ'},
    { ds: 5, nomeUnidade: 'US 345 USF PLANETA DOS MACACOS I'},
    { ds: 5, nomeUnidade: 'US 393 USF UPINHA DIA BONGI NOVO PRADO'},
    { ds: 5, nomeUnidade: 'US 399 USF UPINHA DIA NOVO JIQUIÁ'}
];