name: Exemplo de GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar o valor do segredo
      env:
        SECRET_ENV: ${{ secrets.SECRET_ENV }}
      run: |
        echo "O valor do segredo é: $SECRET_ENV"
